# Getting Started with pandas

In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
import numpy as np
np.random.seed(12345)

In [4]:
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))

In [5]:
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
np.set_printoptions(precision=4, suppress=True)

## Introduction to pandas Data Structures

### Series

In [37]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [38]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [39]:
obj.index  # like range(4)

RangeIndex(start=0, stop=4, step=1)

In [40]:
obj.array

<PandasArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [41]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [42]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [43]:
obj2['a']

-5

In [44]:
obj2['d'] = 6
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [45]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [46]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [51]:
obj2[obj2 != 7]

d    6
a   -5
c    3
dtype: int64

In [52]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [53]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [54]:
import math
math.exp(6)

403.4287934927351

In [55]:
'b' in obj2

True

In [56]:
'e' in obj2

False

In [57]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [58]:
6 in obj2

False

In [59]:
6 in obj2.values

True

In [60]:
5 in [1, 2, 3]

False

### 문제

In [21]:
obj = pd.Series(['c', 'a', 'a', 'b', 'c', 'c']).unique()
obj

array(['c', 'a', 'b'], dtype=object)

In [22]:
obj.sort()

In [23]:
pd.Index(['a', 'b', 'c']).get_indexer(['b', 'a', 'c', 'x'])

array([ 1,  0,  2, -1], dtype=int64)

In [25]:
pd.Index(['a', 'b']).get_indexer(['b', 'a', 'c', 'x']).sum()

-1

In [61]:
s = pd.Series([2, 3, 5, 7], index=[1, 5, 6, 7])
s

1    2
5    3
6    5
7    7
dtype: int64

In [62]:
print(1 in s)
print(2 in s)
print(5 in s)
print(7 in s)

True
False
True
True


In [63]:
6 in s

True

---

In [64]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [65]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [66]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states, name='usadata')
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: usadata, dtype: float64

In [71]:
sd = pd.isnull(obj4)
sd

California     True
Ohio          False
Oregon        False
Texas         False
Name: usadata, dtype: bool

In [72]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
Name: usadata, dtype: bool

In [73]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
Name: usadata, dtype: bool

In [74]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [75]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: usadata, dtype: float64

In [76]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [77]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [78]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [79]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

In [84]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [86]:
frame.head(3)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

In [87]:
frame.tail(3)

state  year  pop
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [88]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [108]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [92]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [93]:
type(frame2.columns)

pandas.core.indexes.base.Index

In [94]:
'year' in frame2.columns

True

In [95]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [96]:
type(frame2['state'])

pandas.core.series.Series

In [97]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [98]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [99]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [100]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [103]:
frame2['debt'] = np.arange(6.) # 행의 길이가 같아야 함, 오류발생
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [104]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [109]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop debt  eastern
one    2000    Ohio  1.5  NaN     True
two    2001    Ohio  1.7  NaN     True
three  2002    Ohio  3.6  NaN     True
four   2001  Nevada  2.4  NaN    False
five   2002  Nevada  2.9  NaN    False
six    2003  Nevada  3.2  NaN    False

In [110]:
del frame2['eastern']

In [111]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [112]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [113]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [114]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [115]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [116]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [117]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [118]:
frame3.index.name = 'year';
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [119]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [120]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### 문제

In [124]:
df = pd.DataFrame({
        "이름": ['이적', '허승', '강소라', '강적'],
        "남여구분": ['남', '남', '여', '남'],
        "학점": [3.2, 2.3, 4.3, 2.9]
     })
df

이름 남여구분   학점
0   이적    남  3.2
1   허승    남  2.3
2  강소라    여  4.3
3   강적    남  2.9

In [126]:
df.loc[3]

이름       강적
남여구분      남
학점      2.9
Name: 3, dtype: object

In [127]:
df.이름

0     이적
1     허승
2    강소라
3     강적
Name: 이름, dtype: object

In [128]:
df['학점']

0    3.2
1    2.3
2    4.3
3    2.9
Name: 학점, dtype: float64

In [129]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [130]:
print(type(df.loc[3]))
print(type(df.이름))
print(type(df['학점']))
print(type(df.index))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.indexes.range.RangeIndex'>


---

### Index Objects

In [ ]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

In [ ]:
index[1:]

index[1] = 'd'  # TypeError

In [ ]:
index[1] = 'd'  # TypeError

In [ ]:
labels = pd.Index(np.arange(3))
labels

In [ ]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

In [ ]:
obj2.index is labels

In [ ]:
frame3

In [ ]:
frame3.columns

In [ ]:
'Ohio' in frame3.columns

In [ ]:
2003 in frame3.index

In [ ]:
'Ohio' in frame3

In [ ]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

## Essential Functionality

### Reindexing

In [7]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [8]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [9]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [10]:
obj3.reindex(range(6))

0      blue
1       NaN
2    purple
3       NaN
4    yellow
5       NaN
dtype: object

In [11]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [12]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [13]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [14]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [15]:
frame.loc[['a', 'c'], ['Texas', 'California']]

Texas  California
a      1           2
c      4           5

In [16]:
#frame['Utah'] = 5

In [17]:
frame.loc[['a', 'c'], ['Texas', 'California']]

Texas  California
a      1           2
c      4           5

In [18]:
frame.loc['a':'c', 'Texas':'California']

Texas  California
a      1           2
c      4           5

In [19]:
frame['Utah'] = 5
frame

Ohio  Texas  California  Utah
a     0      1           2     5
c     3      4           5     5
d     6      7           8     5

In [20]:
states = ['Texas', 'Utah', 'California']
frame.loc[['a', 'c', 'd'], states]
#frame.loc[['a', 'c', 'd'], ['Texas', 'Utah', 'California']] #위와 동일

Texas  Utah  California
a      1     5           2
c      4     5           5
d      7     5           8

In [21]:
tuples = [
   ('cobra', 'mark i'), ('cobra', 'mark ii'),
   ('sidewinder', 'mark i'), ('sidewinder', 'mark ii'),
   ('viper', 'mark ii'), ('viper', 'mark iii')
]
index = pd.MultiIndex.from_tuples(tuples)
values = [[12, 2], [0, 4], [10, 20],
        [1, 4], [7, 1], [16, 36]]
df = pd.DataFrame(values, columns=['max_speed', 'shield'], index=index)
df

max_speed  shield
cobra      mark i           12       2
           mark ii           0       4
sidewinder mark i           10      20
           mark ii           1       4
viper      mark ii           7       1
           mark iii         16      36

In [22]:
df.loc['cobra']

max_speed  shield
mark i          12       2
mark ii          0       4

In [23]:
df.loc[('cobra', 'mark ii')]

max_speed    0
shield       4
Name: (cobra, mark ii), dtype: int64

### Dropping Entries from an Axis

In [24]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [25]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [26]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [27]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [28]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [29]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [30]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [31]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [32]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### Indexing, Selection, and Filtering

In [33]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [34]:
obj['b']

1.0

In [35]:
obj[1]

1.0

In [36]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [37]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [38]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [39]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [40]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [41]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [42]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [43]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [44]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [45]:
data[:2] #행 선택

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [47]:
data['three'] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [48]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [46]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [49]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### Selection with loc and iloc

In [ ]:
data

In [ ]:
data.loc['Colorado', ['two', 'three']]

In [ ]:
data.iloc[2, [3, 0, 1]]

In [ ]:
data.iloc[2]

In [ ]:
data.iloc[[1, 2], [3, 0, 1]]

In [ ]:
data.loc[:'Utah', 'two']

In [ ]:
data.iloc[:, :3]

In [ ]:
data.iloc[:, :3][data.three > 5]

### Integer Indexes

ser = pd.Series(np.arange(3.))
ser
ser[-1]

In [ ]:
ser = pd.Series(np.arange(3.))
ser

In [ ]:
ser[0]
#ser[-1] # 색인 자체가 정수, -1을 라벨로 인지하고 검색, 오류 발생

In [ ]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2[-1]

In [ ]:
ser[:1]

In [ ]:
ser.loc[:1]

In [ ]:
ser.iloc[:1]

### Arithmetic and Data Alignment

In [ ]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
s1

In [ ]:
s2

In [ ]:
s1 + s2

In [ ]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

In [ ]:
df2

In [ ]:
df1 + df2

In [ ]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})
df1

In [ ]:
df2

In [ ]:
df1 - df2

#### Arithmetic methods with fill values

In [ ]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df1

In [ ]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.nan
df2

In [ ]:
df1 + df2

In [ ]:
df1.add(df2, fill_value=0)

In [ ]:
1 / df1

In [ ]:
df1.rdiv(1) # 1 / df1 와 같은 연산

In [ ]:
df1.reindex(columns=df2.columns, fill_value=0)

#### Operations between DataFrame and Series

In [ ]:
arr = np.arange(12.).reshape((3, 4))
arr

In [ ]:
arr[0]

In [ ]:
arr - arr[0]

In [ ]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

In [ ]:
series = frame.iloc[0]
series

In [ ]:
frame - series

In [ ]:
frame

In [ ]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
series2

In [ ]:
frame + series2

In [ ]:
series3 = frame['d']
series3

In [ ]:
frame

In [ ]:
frame.sub(series3, axis=0)

In [ ]:
frame.sub(series3)

### Function Application and Mapping

In [52]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.204708  0.478943 -0.519439
Ohio   -0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189 -1.296221

In [53]:
np.abs(frame)

b         d         e
Utah    0.204708  0.478943  0.519439
Ohio    0.555730  1.965781  1.393406
Texas   0.092908  0.281746  0.769023
Oregon  1.246435  1.007189  1.296221

In [54]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.802165
d    1.684034
e    2.689627
dtype: float64

In [ ]:
frame.apply(f, axis='columns')

In [ ]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame

In [ ]:
frame.apply(f)

In [ ]:
frame.apply(f, axis=1)

In [ ]:
format = lambda x: '%.2f' % x
frame

In [ ]:
frame.applymap(format)

In [ ]:
frame['e'].map(format)

### 문제

In [7]:
df = pd.DataFrame([[-1, 2], [1, -2]])
df

0  1
0 -1  2
1  1 -2

In [10]:
ab = np.abs(df)
ab

0  1
0  1  2
1  1  2

In [13]:
ab.sum()

0    2
1    4
dtype: int64

In [14]:
a = pd.DataFrame([[-1, 2], [1, -2]])
np.abs(a).sum().sum()

6

### Sorting and Ranking

In [35]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [36]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [43]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [44]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [ ]:
frame.sort_index(axis=1)

In [ ]:
frame.sort_index(axis=1, ascending=False)

In [ ]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

In [ ]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

In [ ]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

In [ ]:
frame.sort_values()

In [ ]:
frame.sort_values(by='b')

In [ ]:
frame.sort_values(by=['a', 'b'])

* 다양한 정렬

In [ ]:
frame.sort_values?

In [ ]:
df = pd.DataFrame({
    'col1': ['A', 'A', 'B', np.nan, 'D', 'C'],
    'col2': [2, 1, 9, 8, 7, 4],
    'col3': [0, 1, 9, 4, 2, 3],
})
df

In [ ]:
df.sort_values(by=['col1'])

In [ ]:
df.sort_values(by=['col1', 'col2'])

In [ ]:
df.sort_values(by='col1', ascending=False)

In [ ]:
df.sort_values(by='col1', ascending=False, na_position='first')

In [ ]:
df

In [ ]:
df.sort_values(by=3, axis=1)

In [55]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [56]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [57]:
# Assign tie values the maximum rank in the group
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [58]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [59]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [ ]:
frame.rank(axis=1)

In [62]:
frame.rank()

b    a    c
0  3.0  1.5  2.0
1  4.0  3.5  3.0
2  1.0  1.5  4.0
3  2.0  3.5  1.0

In [61]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [60]:
frame.rank(axis=0)

b    a    c
0  3.0  1.5  2.0
1  4.0  3.5  3.0
2  1.0  1.5  4.0
3  2.0  3.5  1.0

### Axis Indexes with Duplicate Labels

In [ ]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

In [ ]:
obj.index.is_unique

In [ ]:
obj['a']

In [ ]:
obj['c']

In [ ]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

In [ ]:
df.loc['b']

In [ ]:
df[1] #열 자체의 레이블이 1

In [ ]:
df[0] #열 자체의 레이블이 0

## Summarizing and Computing Descriptive Statistics

In [26]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [29]:
df.sum(axis='index')

one    9.25
two   -5.80
dtype: float64

In [30]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [31]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [32]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [33]:
df.idxmax()

one    b
two    d
dtype: object

In [34]:
df.idxmax(axis=1)

a    one
b    one
c    NaN
d    one
dtype: object

In [35]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [36]:
df.cumsum(axis=1)

one   two
a  1.40   NaN
b  7.10  2.60
c   NaN   NaN
d  0.75 -0.55

In [37]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [38]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [41]:
obj = pd.Series(['b', 'ab', 'a', 'b', 'c', 'b'] * 4)

In [42]:
obj.describe()

count     24
unique     4
top        b
freq      12
dtype: object

### Correlation and Covariance

conda install pandas-datareader

In [43]:
price = pd.read_pickle('examples/yahoo_price.pkl')
price.head()

AAPL        GOOG         IBM       MSFT
Date                                                    
2010-01-04  27.990226  313.062468  113.304536  25.884104
2010-01-05  28.038618  311.683844  111.935822  25.892466
2010-01-06  27.592626  303.826685  111.208683  25.733566
2010-01-07  27.541619  296.753749  110.823732  25.465944
2010-01-08  27.724725  300.709808  111.935822  25.641571

In [44]:
price.shape

(1714, 4)

In [ ]:
volume = pd.read_pickle('examples/yahoo_volume.pkl')
volume.head()

In [ ]:
volume.shape

import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [ ]:
price.pct_change? # 전날 대비 변화율

In [ ]:
returns = price.pct_change()
returns.tail()

In [ ]:
returns['MSFT'].corr(returns['IBM'])

In [ ]:
returns['MSFT'].cov(returns['IBM'])

In [ ]:
returns.MSFT.corr(returns.IBM)

In [ ]:
returns.corr()

In [ ]:
returns.cov()

In [ ]:
returns.corrwith(returns.IBM)

In [ ]:
returns.corrwith(volume, axis=1)

In [ ]:
import pandas_datareader.data as web

In [ ]:
conda install pandas-datareader

In [ ]:
import pandas_datareader.data as web

In [ ]:
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}
all_data['IBM'].head()

In [ ]:
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
price

In [ ]:
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})
volume

### Unique Values, Value Counts, and Membership

In [45]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [46]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [47]:
obj.value_counts() # 값을 내림차 순으로

a    3
c    3
b    2
d    1
dtype: int64

In [48]:
pd.value_counts(obj.values, sort=False)

a    3
d    1
c    3
b    2
dtype: int64

In [49]:
pd.value_counts(obj.values, sort=True)

a    3
c    3
b    2
d    1
dtype: int64

In [50]:
pd.value_counts(obj.values).sort_index() # 인덱스를 오름차 순으로

a    3
b    2
c    3
d    1
dtype: int64

In [51]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [52]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [53]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [54]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
to_match

0    c
1    a
2    b
3    b
4    c
5    a
dtype: object

In [55]:
unique_vals = pd.Series(['c', 'b', 'a'])
unique_vals

0    c
1    b
2    a
dtype: object

In [56]:
pd.Index(unique_vals)

Index(['c', 'b', 'a'], dtype='object')

In [57]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [59]:
index = pd.Index(['c', 'a', 'b'])
index.get_indexer(['a', 'b', 'c', 'x'])

array([ 1,  2,  0, -1], dtype=int64)

In [60]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [61]:
data.apply(pd.value_counts) #축 0에 따라 값의 수를 저장

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  NaN  2.0  1.0
3  2.0  2.0  NaN
4  2.0  NaN  2.0
5  NaN  NaN  1.0

In [62]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [63]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [64]:
data.apply(pd.value_counts, axis=1)

1    2    3    4    5
0  2.0  1.0  NaN  NaN  NaN
1  NaN  NaN  2.0  NaN  1.0
2  1.0  1.0  NaN  1.0  NaN
3  NaN  1.0  1.0  1.0  NaN
4  NaN  NaN  1.0  2.0  NaN

In [65]:
result = data.apply(pd.value_counts, axis=1).fillna(0)
result

1    2    3    4    5
0  2.0  1.0  0.0  0.0  0.0
1  0.0  0.0  2.0  0.0  1.0
2  1.0  1.0  0.0  1.0  0.0
3  0.0  1.0  1.0  1.0  0.0
4  0.0  0.0  1.0  2.0  0.0

### 문제

## Conclusion

In [ ]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS

In [ ]:
df = pd.DataFrame(np.arange(20).reshape(4, 5),
                 index = list('ABCD'), 
                 columns = ['java', 'C', 'C++', 'python', 'Go'])
df

In [ ]:
df[['java', 'C']]

In [ ]:
df[['java', 'C']][1:3]

In [ ]:
df[1:3]

In [ ]:
df.iloc[3]

In [ ]:
df.iloc[3, 4]

In [ ]:
df['C']

In [ ]:
df.drop('B')

In [ ]:
df

In [ ]:
df.drop('java', axis=1)

In [ ]:
df

In [ ]:
df

In [ ]:
df.iloc[0, 0] = np.nan

In [ ]:
df

In [ ]:
df.iloc[0, 0]

In [ ]:
df.loc['A', 'java']

In [ ]:
df.loc[['A'], ['java']]

In [ ]:
df[0:1]

In [ ]:
df

In [ ]:
df[df>3]

In [ ]:
df>3

In [ ]:
df['python']>8

In [ ]:
df[df['python']>8]

In [ ]:
df[[True, True, True, True, True]]

In [ ]:
df

In [ ]:
df[7<=df]

In [ ]:
df1 = pd.DataFrame(np.arange(6).reshape(2, 3), 
                 index = list('AB'))
df1

In [ ]:
df2 = pd.DataFrame(np.arange(6).reshape(2, 3), 
                 columns = list('ABC'))
df2

In [ ]:
df1 + df2

In [ ]:
s = pd.Series(range(3), index=list('ABC'))
s

In [ ]:
df1

In [ ]:
df1 + s

In [ ]:
df1 + s

In [ ]:
df1.add(s, axis=0)